// frontend-vue/src/components/Chrome.vue
<template>
  <!-- Brand is rendered by the parent App via <Brand /> -->
</template>

<script lang="ts">
import { defineComponent, h, ref as vRef, onMounted, onBeforeUnmount } from 'vue';
import { useGraph } from '@/composables/useGraph';

const SHORTCUTS = [
  { keys: ['/'], label: 'Search' },
  { keys: ['⌘', 'K'], label: 'Search (any field)' },
  { keys: ['F'], label: 'Filter to selected family' },
  { keys: ['↑', '↓'], label: 'Walk ancestors / descendants' },
  { keys: ['Esc'], label: 'Close panel / clear filter' },
  { keys: ['T'], label: 'Toggle theme' },
  { keys: ['?'], label: 'Toggle this list' },
];

export const Brand = defineComponent({
  name: 'Brand',
  setup() {
    const g = useGraph();
    return () => {
      const data = g.data.value;
      if (!data) return null;
      return h('div', { class: 'brand' }, [
        h('span', { class: 'brand-mark', 'aria-hidden': 'true' }, [h('span', { class: 'brand-mark-dot' })]),
        h('div', { class: 'brand-text' }, [
          h('span', { class: 'brand-title' }, 'DistroMap'),
          h('span', { class: 'brand-sub' }, 'the Linux knowledge graph'),
        ]),
        h('div', { class: 'brand-stats' }, [
          h('div', { class: 'brand-stat' }, [h('strong', String(data.meta.active)), h('span', 'active')]),
          h('div', { class: 'brand-stat' }, [h('strong', String(data.meta.discontinued)), h('span', 'disc.')]),
          h('div', { class: 'brand-stat' }, [h('strong', String(Math.max(0, data.meta.families - 1))), h('span', 'families')]),
        ]),
      ]);
    };
  },
});

export const KeyboardHints = defineComponent({
  name: 'KeyboardHints',
  setup() {
    const g = useGraph();
    return () =>
      h('div', { class: ['kbd-hints', g.kbdOpen.value ? 'is-open' : ''] }, [
        h('button', {
          class: 'kbd-hints-toggle',
          'aria-label': 'Toggle keyboard shortcuts',
          onClick: () => (g.kbdOpen.value = !g.kbdOpen.value),
        }, [h('span', { class: 'kbd-hints-toggle-key' }, '?')]),
        h('div', { class: 'kbd-hints-panel' }, [
          h('h3', 'Keyboard shortcuts'),
          h('ul', SHORTCUTS.map((s) =>
            h('li', { key: s.label }, [
              h('span', { class: 'kbd-keys' }, s.keys.map((k, i) => h('kbd', { key: i }, k))),
              h('span', { class: 'kbd-label' }, s.label),
            ]),
          )),
        ]),
      ]);
  },
});

export const ThemeToggle = defineComponent({
  name: 'ThemeToggle',
  setup() {
    const g = useGraph();
    const animating = vRef(false);
    return () =>
      h('button', {
        class: 'theme-toggle',
        'aria-label': `Switch to ${g.theme.value === 'dark' ? 'light' : 'dark'} theme`,
        title: `Switch to ${g.theme.value === 'dark' ? 'light' : 'dark'} theme`,
        onClick: () => {
          if (animating.value) return;
          animating.value = true;
          g.toggleTheme();
          setTimeout(() => (animating.value = false), 500);
        },
      }, [
        h('span', { class: 'theme-toggle-icon' }, g.theme.value === 'dark' ? '☀' : '☾'),
      ]);
  },
});

export default defineComponent({ name: 'ChromeStub', setup: () => () => null });
// keep tree-shaking from dropping onMounted/onBeforeUnmount imports if needed elsewhere
void onMounted; void onBeforeUnmount;
</script>

// frontend/src/components/Chrome.tsx
import { useRef } from 'react';
import type { GraphData } from '@shared/types';

interface BrandProps {
  data: GraphData;
}

export function Brand({ data }: BrandProps) {
  return (
    <div className="brand">
      <span className="brand-mark" aria-hidden>
        <span className="brand-mark-dot" />
      </span>
      <div className="brand-text">
        <span className="brand-title">DistroMap</span>
        <span className="brand-sub">the Linux knowledge graph</span>
      </div>
      <div className="brand-stats">
        <div className="brand-stat">
          <strong>{data.meta.active}</strong>
          <span>active</span>
        </div>
        <div className="brand-stat">
          <strong>{data.meta.discontinued}</strong>
          <span>disc.</span>
        </div>
        <div className="brand-stat">
          <strong>{data.meta.families - 1}</strong>
          <span>families</span>
        </div>
      </div>
    </div>
  );
}

interface KeyboardHintsProps {
  show: boolean;
  onToggle: () => void;
}

const SHORTCUTS = [
  { keys: ['/'], label: 'Search' },
  { keys: ['⌘', 'K'], label: 'Search (any field)' },
  { keys: ['F'], label: 'Filter to selected family' },
  { keys: ['↑', '↓'], label: 'Walk ancestors / descendants' },
  { keys: ['Esc'], label: 'Close panel / clear filter' },
  { keys: ['T'], label: 'Toggle theme' },
  { keys: ['?'], label: 'Toggle this list' },
];

/* ===== Theme Toggle ===== */

export function ThemeToggle({ theme, onToggle }: { theme: 'dark' | 'light'; onToggle: () => void }) {
  const spinning = useRef(false);
  const btnRef = useRef<HTMLButtonElement>(null);

  const handleToggle = () => {
    if (spinning.current) return;
    spinning.current = true;
    onToggle();
    const el = btnRef.current;
    if (el) {
      el.classList.add('theme-toggle--anim');
      setTimeout(() => {
        el.classList.remove('theme-toggle--anim');
        spinning.current = false;
      }, 500);
    }
  };

  return (
    <button
      ref={btnRef}
      className="theme-toggle"
      onClick={handleToggle}
      aria-label={`Switch to ${theme === 'dark' ? 'light' : 'dark'} theme`}
      title={`Switch to ${theme === 'dark' ? 'light' : 'dark'} theme`}
    >
      <span className="theme-toggle-icon">
        {theme === 'dark' ? '☀' : '☾'}
      </span>
    </button>
  );
}

export function KeyboardHints({ show, onToggle }: KeyboardHintsProps) {
  return (
    <div className={`kbd-hints ${show ? 'is-open' : ''}`}>
      <button className="kbd-hints-toggle" onClick={onToggle} aria-label="Toggle keyboard shortcuts">
        <span className="kbd-hints-toggle-key">?</span>
      </button>
      <div className="kbd-hints-panel">
        <h3>Keyboard shortcuts</h3>
        <ul>
          {SHORTCUTS.map((s) => (
            <li key={s.label}>
              <span className="kbd-keys">
                {s.keys.map((k, idx) => (
                  <kbd key={idx}>{k}</kbd>
                ))}
              </span>
              <span className="kbd-label">{s.label}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
