// frontend-vue/src/components/SearchBar.vue
<template>
  <div class="search-bar" :class="{ 'is-open': open }">
    <div class="search-input-wrap">
      <span class="search-icon" aria-hidden>⌕</span>
      <input
        ref="inputEl"
        v-model="g.searchQuery.value"
        class="search-input"
        placeholder='Search 280+ distros or "family: debian" / "init: openrc" / "country: Germany"'
        aria-label="Search distros"
        @focus="open = true"
        @blur="onBlur"
      />
      <button class="search-kbd" aria-label="Keyboard shortcut">/</button>
    </div>

    <div v-if="chips.length" class="search-chips">
      <span v-for="c in chips" :key="c" class="search-chip">{{ c }}</span>
    </div>

    <div v-if="open && suggestions.length" class="search-dropdown" role="listbox">
      <button
        v-for="s in suggestions"
        :key="s.id"
        class="search-result"
        @mousedown.prevent="pick(s.id)"
        @mouseenter="g.searchHoveredId.value = s.id"
        @mouseleave="g.searchHoveredId.value = null"
      >
        <span class="search-result-name">{{ s.name }}</span>
        <span class="search-result-meta">
          <span v-if="s.packageManager">pkg: {{ s.packageManager }}</span>
          <span v-if="s.initSystem">init: {{ s.initSystem }}</span>
          <span v-if="s.country">{{ s.country }}</span>
        </span>
      </button>
    </div>

    <div v-if="open && g.searchQuery.value.length >= 2 && !suggestions.length" class="search-empty">
      No matches for “{{ g.searchQuery.value }}”.
    </div>

    <button v-if="g.searchQuery.value" class="search-clear" @click="g.searchQuery.value = ''" aria-label="Clear search">
      Clear
    </button>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch, onMounted } from 'vue';
import { useGraph } from '@/composables/useGraph';

const g = useGraph();
const inputEl = ref<HTMLInputElement | null>(null);
const open = ref(false);

const suggestions = computed(() => g.filteredResults.value.slice(0, 6));

const chips = computed<string[]>(() => {
  const f = g.parsedQuery.value.filter;
  const out: string[] = [];
  if (f.family) out.push(`family: ${f.family}`);
  if (f.init) out.push(`init: ${f.init}`);
  if (f.pkg) out.push(`pkg: ${f.pkg}`);
  if (f.country) out.push(`country: ${f.country}`);
  if (f.status) out.push(`status: ${f.status}`);
  if (f.release) out.push(`release: ${f.release}`);
  if (f.license) out.push(`license: ${f.license}`);
  return out;
});

function pick(id: string) {
  g.selectedId.value = id;
  open.value = false;
}

function onBlur() {
  setTimeout(() => (open.value = false), 120);
}

// Focus when the focus signal changes (keyboard shortcut).
watch(() => g.requestSearchFocus.value, () => inputEl.value?.focus());
onMounted(() => inputEl.value?.focus());
</script>

// frontend/src/components/SearchBar.tsx
import { useEffect, useMemo, useRef, useState } from 'react';
import type { Distro } from '@shared/types';
import { parseSearch } from '@/lib/query';
import { fetchSearch } from '@/lib/api';

interface SearchBarProps {
  value: string;
  onChange: (v: string) => void;
  results: Distro[];
  onPick: (id: string) => void;
  focusSignal?: number;
}

export function SearchBar({ value, onChange, results, onPick, focusSignal }: SearchBarProps) {
  const inputRef = useRef<HTMLInputElement>(null);
  const [open, setOpen] = useState(false);
  const [remoteResults, setRemoteResults] = useState<Distro[] | null>(null);

  // Focus the input whenever the external focusSignal changes (triggered by keyboard shortcuts)
  useEffect(() => {
    if (focusSignal !== undefined) {
      inputRef.current?.focus();
    }
  }, [focusSignal]);

  const parsed = useMemo(() => parseSearch(value), [value]);

  // When the user types a non-trivial query, prefetch suggestions.
  useEffect(() => {
    if (!value || value.trim().length < 2) {
      setRemoteResults(null);
      return;
    }
    const handle = setTimeout(() => {
      fetchSearch(value).then(setRemoteResults).catch(() => setRemoteResults(null));
    }, 180);
    return () => clearTimeout(handle);
  }, [value]);

  const suggestions = (remoteResults ?? results).slice(0, 6);

  const chips: string[] = [];
  if (parsed.filter.family) chips.push(`family: ${parsed.filter.family}`);
  if (parsed.filter.init) chips.push(`init: ${parsed.filter.init}`);
  if (parsed.filter.pkg) chips.push(`pkg: ${parsed.filter.pkg}`);
  if (parsed.filter.country) chips.push(`country: ${parsed.filter.country}`);
  if (parsed.filter.status) chips.push(`status: ${parsed.filter.status}`);
  if (parsed.filter.release) chips.push(`release: ${parsed.filter.release}`);
  if (parsed.filter.license) chips.push(`license: ${parsed.filter.license}`);

  return (
    <div className={`search-bar ${open ? 'is-open' : ''}`}>
      <div className="search-input-wrap">
        <span className="search-icon" aria-hidden>⌕</span>
        <input
          ref={inputRef}
          value={value}
          onChange={(e) => onChange(e.target.value)}
          onFocus={() => setOpen(true)}
          onBlur={() => setTimeout(() => setOpen(false), 120)}
          placeholder='Search 280+ distros or "family: debian" / "init: openrc" / "country: Germany"'
          className="search-input"
          aria-label="Search distros"
        />
        <button className="search-kbd" aria-label="Keyboard shortcut">/</button>
      </div>

      {chips.length > 0 && (
        <div className="search-chips">
          {chips.map((c) => (
            <span key={c} className="search-chip">
              {c}
            </span>
          ))}
        </div>
      )}

      {open && suggestions.length > 0 && (
        <div className="search-dropdown" role="listbox">
          {suggestions.map((s) => (
            <button key={s.id} className="search-result" onClick={() => onPick(s.id)}>
              <span className="search-result-name">{s.name}</span>
              <span className="search-result-meta">
                {s.packageManager && <span>pkg: {s.packageManager}</span>}
                {s.initSystem && <span>init: {s.initSystem}</span>}
                {s.country && <span>{s.country}</span>}
              </span>
            </button>
          ))}
        </div>
      )}

      {open && value.length >= 2 && suggestions.length === 0 && (
        <div className="search-empty">No matches for “{value}”.</div>
      )}

      {value && (
        <button className="search-clear" onClick={() => onChange('')} aria-label="Clear search">
          Clear
        </button>
      )}
    </div>
  );
}
